GET http://localhost:3000/status http/1.1
#######

POST http://localhost:3000/convert-html-to-pdf  http/1.1
content-type: application/json

{
    "htmlSrc": "C:/NAHUEL/Proyectos/Conversor-html-a-pdf/ejemplo/cuerpo.htm",
    "outputPath": "C:/Users/HP/Documents/programas-utilidades/html-to-pdf/ejemplo/output.pdf",
    "headerTemplate": "<div>Encabezado personalizado</div>",
    "footerTemplate": "<div style='text-align:center;'>Página <span class='pageNumber'></span> de <span class='totalPages'></span></div>",
    "margin": {
        "top": "20mm",
        "bottom": "30mm"
    },
    "cssPath": "styles.css"
}